language: php

php:
  - 5.2
  - 5.3
  - 5.4

env:
  - YII_VERSION=1.1.10

before_script:
  - php protected/vendor/vendors.php

script:
  - phpunit --configuration protected/tests/phpunit.xml protected/tests/unit/MessageTest.php